spring.application.name=demo

# 본인이 생성한 DB 이름, 사용자 계정, 비밀번호로 변경해야 합니다.
spring.datasource.url=jdbc:postgresql://localhost:5432/likelion_db
spring.datasource.username=hwangsungmin
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA 설정 (테이블 자동 생성 및 SQL 쿼리 로그 확인)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true